//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Framework.Tools.NAntConsole.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDS.Framework.Tools.NAntConsole.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutBoxVersion {
            get {
                return ResourceManager.GetString("AboutBoxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch {0} created at {1}..
        /// </summary>
        internal static string BranchCreated {
            get {
                return ResourceManager.GetString("BranchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out {0} to {1}....
        /// </summary>
        internal static string CheckingOut {
            get {
                return ResourceManager.GetString("CheckingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationCaption {
            get {
                return ResourceManager.GetString("ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to install product {0} ?.
        /// </summary>
        internal static string ConfirmInstall {
            get {
                return ResourceManager.GetString("ConfirmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall product {0} ?.
        /// </summary>
        internal static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show projects that depend on :.
        /// </summary>
        internal static string DependentProjects {
            get {
                return ResourceManager.GetString("DependentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExecutionInfo] Machine : {0} - Username : {1}\{2} - Time : {3:yyyy-MM-dd HH:mm}.
        /// </summary>
        internal static string DisplayExecutionInfo {
            get {
                return ResourceManager.GetString("DisplayExecutionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing log to eventlog : {0}.
        /// </summary>
        internal static string DisplayOnlyErrorWritingEventLog {
            get {
                return ResourceManager.GetString("DisplayOnlyErrorWritingEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing log to {0} : {1}.
        /// </summary>
        internal static string DisplayOnlyErrorWritingLog {
            get {
                return ResourceManager.GetString("DisplayOnlyErrorWritingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string EnvironmentAsk {
            get {
                return ResourceManager.GetString("EnvironmentAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string EnvironmentName {
            get {
                return ResourceManager.GetString("EnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment directory {0} not found..
        /// </summary>
        internal static string EnvironmnentDirNotFound {
            get {
                return ResourceManager.GetString("EnvironmnentDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmnent file &quot;{0}&quot; already exists..
        /// </summary>
        internal static string EnvironmnentFileExists {
            get {
                return ResourceManager.GetString("EnvironmnentFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to checkout in path {0} : the directory already exists..
        /// </summary>
        internal static string ErrorCheckOutDirectoryExists {
            get {
                return ResourceManager.GetString("ErrorCheckOutDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading project file {0} : {1}..
        /// </summary>
        internal static string ErrorLoadingProjectFile {
            get {
                return ResourceManager.GetString("ErrorLoadingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error : {0}..
        /// </summary>
        internal static string ExecutionError {
            get {
                return ResourceManager.GetString("ExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting package {0} into {1}....
        /// </summary>
        internal static string ExtractingPackage {
            get {
                return ResourceManager.GetString("ExtractingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path {0} has pending modifications. Operation aborted..
        /// </summary>
        internal static string HasPendingModifications {
            get {
                return ResourceManager.GetString("HasPendingModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help not avalaible..
        /// </summary>
        internal static string HelpNotAvalaible {
            get {
                return ResourceManager.GetString("HelpNotAvalaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help unavailable for task {0}..
        /// </summary>
        internal static string HelpUnavailable {
            get {
                return ResourceManager.GetString("HelpUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0} command....
        /// </summary>
        internal static string InitUICommand {
            get {
                return ResourceManager.GetString("InitUICommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will try to analyse a whole svn tree to find depend projects.
        ///This may take a while, so you should try to narrow as much as you can the search start tree.
        ///Do you wish to continue ?.
        /// </summary>
        internal static string LinkAnalysisConfirm {
            get {
                return ResourceManager.GetString("LinkAnalysisConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading deploy file {0}....
        /// </summary>
        internal static string LoadingDeployFile {
            get {
                return ResourceManager.GetString("LoadingDeployFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local folder is not under SVN source control. Operation aborted..
        /// </summary>
        internal static string LocalFolderNotUnderSourceControl {
            get {
                return ResourceManager.GetString("LocalFolderNotUnderSourceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAntConsole - {0}.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that NAntConsole is missing some information to operate on this svn folder. This svn folder might not have been created from NAntConsole.
        ///This operation cannot continue..
        /// </summary>
        internal static string MissingBranchProperties {
            get {
                return ResourceManager.GetString("MissingBranchProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch.
        /// </summary>
        internal static string NewBranch {
            get {
                return ResourceManager.GetString("NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update found.
        /// </summary>
        internal static string NewUpdateCaption {
            get {
                return ResourceManager.GetString("NewUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of NAntConsole ({0}) has been found in the repository &quot;{1}&quot;. Do you want to update now ?
        ///All running instances of NAntConsole will be shut down..
        /// </summary>
        internal static string NewUpdateFound {
            get {
                return ResourceManager.GetString("NewUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update was found..
        /// </summary>
        internal static string NewUpdateNotFound {
            get {
                return ResourceManager.GetString("NewUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open parent folder....
        /// </summary>
        internal static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file in Visual Studio....
        /// </summary>
        internal static string OpenInVS {
            get {
                return ResourceManager.GetString("OpenInVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error trying to open Visual Studio..
        /// </summary>
        internal static string OpenInVSError {
            get {
                return ResourceManager.GetString("OpenInVSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dependencies of :.
        /// </summary>
        internal static string ProjectDependencies {
            get {
                return ResourceManager.GetString("ProjectDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes not avalaible..
        /// </summary>
        internal static string ReleaseNotesNotAvalaible {
            get {
                return ResourceManager.GetString("ReleaseNotesNotAvalaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are pending conflicts. Please resolve them manually..
        /// </summary>
        internal static string ResolveConflicts {
            get {
                return ResourceManager.GetString("ResolveConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NAntConsole] - directory {0} remotely created..
        /// </summary>
        internal static string SvnCreateDirectoryLogMessage {
            get {
                return ResourceManager.GetString("SvnCreateDirectoryLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} loaded..
        /// </summary>
        internal static string SvnExplorerLoaded {
            get {
                return ResourceManager.GetString("SvnExplorerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        internal static string SvnExplorerLoading {
            get {
                return ResourceManager.GetString("SvnExplorerLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged from {0} at {1}..
        /// </summary>
        internal static string SvnLogCommitAfterMerge {
            get {
                return ResourceManager.GetString("SvnLogCommitAfterMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NAntConsole] Branch {0} remotely created..
        /// </summary>
        internal static string SvnLogCreatingBranch {
            get {
                return ResourceManager.GetString("SvnLogCreatingBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NAntConsole] Setting property {0} = {1}..
        /// </summary>
        internal static string SvnLogSetProperty {
            get {
                return ResourceManager.GetString("SvnLogSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Open a project file&gt;.
        /// </summary>
        internal static string ToolStripLabelLocationOpenProjectFile {
            get {
                return ResourceManager.GetString("ToolStripLabelLocationOpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ToolStripStatusLabel {
            get {
                return ResourceManager.GetString("ToolStripStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}....
        /// </summary>
        internal static string ToolStripStatusLabelExecutingTarget {
            get {
                return ResourceManager.GetString("ToolStripStatusLabelExecutingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} executed with errors..
        /// </summary>
        internal static string ToolStripStatusLabelExecutionKo {
            get {
                return ResourceManager.GetString("ToolStripStatusLabelExecutionKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} executed successfully..
        /// </summary>
        internal static string ToolStripStatusLabelExecutionOk {
            get {
                return ResourceManager.GetString("ToolStripStatusLabelExecutionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates are avalaible....
        /// </summary>
        internal static string UpdateAvalaibleToolTip {
            get {
                return ResourceManager.GetString("UpdateAvalaibleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateCaption {
            get {
                return ResourceManager.GetString("UpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update....
        /// </summary>
        internal static string UpdateToolTip {
            get {
                return ResourceManager.GetString("UpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your NAntConsole version ({0}) was created before this package ({1}). Please upgrade your copy of NAntConsole..
        /// </summary>
        internal static string VersionError {
            get {
                return ResourceManager.GetString("VersionError", resourceCulture);
            }
        }
    }
}
