//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Framework.Tools.NAntConsole.NAntConsoleTasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDS.Framework.Tools.NAntConsole.NAntConsoleTasks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding access rights {0} to NT Account {1} on {2}....
        /// </summary>
        internal static string AddAccessRuleAdding {
            get {
                return ResourceManager.GetString("AddAccessRuleAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-compiling asp.net on {0} to {1}....
        /// </summary>
        internal static string ASPNetPreCompiling {
            get {
                return ResourceManager.GetString("ASPNetPreCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding job &quot;{0}&quot;....
        /// </summary>
        internal static string ATAddJobAdding {
            get {
                return ResourceManager.GetString("ATAddJobAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding trigger {0}....
        /// </summary>
        internal static string ATAddJobAddingTrigger {
            get {
                return ResourceManager.GetString("ATAddJobAddingTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting job &quot;{0}&quot;....
        /// </summary>
        internal static string ATDelJobDeleting {
            get {
                return ResourceManager.GetString("ATDelJobDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job &quot;{0}&quot; not found..
        /// </summary>
        internal static string ATDelJobNotFound {
            get {
                return ResourceManager.GetString("ATDelJobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} not found..
        /// </summary>
        internal static string BaseAccessRuleDirNotFound {
            get {
                return ResourceManager.GetString("BaseAccessRuleDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found..
        /// </summary>
        internal static string BaseAccessRuleFileNotFound {
            get {
                return ResourceManager.GetString("BaseAccessRuleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property {0} = {1}.
        /// </summary>
        internal static string BaseCOMTaskApplyProperty {
            get {
                return ResourceManager.GetString("BaseCOMTaskApplyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for {1}. Possible values are :.
        /// </summary>
        internal static string BaseCOMTaskFormatPossibleValues {
            get {
                return ResourceManager.GetString("BaseCOMTaskFormatPossibleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuting target {0}....
        /// </summary>
        internal static string BuildComponentExecuteTarget {
            get {
                return ResourceManager.GetString("BuildComponentExecuteTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component file not found : {0}..
        /// </summary>
        internal static string BuildComponentFileNotFound {
            get {
                return ResourceManager.GetString("BuildComponentFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing VB6 dll {0}..
        /// </summary>
        internal static string BuildComponentMissingVB6Artifact {
            get {
                return ResourceManager.GetString("BuildComponentMissingVB6Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component {0} is not supported by the build-components task..
        /// </summary>
        internal static string BuildComponentNotSupported {
            get {
                return ResourceManager.GetString("BuildComponentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking dependencies for project {0}....
        /// </summary>
        internal static string CheckVB6DependenciesCheck {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with reference {0} ({1}) : the guid doesn&apos;t match - expected {2} != actual {3}..
        /// </summary>
        internal static string CheckVB6DependenciesGuidNotMatch {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesGuidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with reference {0} ({1}) : the path {2} is not relative..
        /// </summary>
        internal static string CheckVB6DependenciesPathRooted {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesPathRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with reference {0} ({1}) : the file {2} doesn&apos;t exist..
        /// </summary>
        internal static string CheckVB6DependenciesReferenceMissing {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesReferenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with reference {0} ({1}) : the file {2} is not in the project folder..
        /// </summary>
        internal static string CheckVB6DependenciesReferenceNotInProjectFolder {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesReferenceNotInProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping path rooted check for {0}..
        /// </summary>
        internal static string CheckVB6DependenciesSkippingDirectory {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesSkippingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with reference {0} ({1}) : the version doesn&apos;t match - expected {2} != actual {3}..
        /// </summary>
        internal static string CheckVB6DependenciesWrongVersion {
            get {
                return ResourceManager.GetString("CheckVB6DependenciesWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding component {0} to application {1}....
        /// </summary>
        internal static string COMCreateApplicationAddComponent {
            get {
                return ResourceManager.GetString("COMCreateApplicationAddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding role {0} to {1}....
        /// </summary>
        internal static string COMCreateApplicationAddRole {
            get {
                return ResourceManager.GetString("COMCreateApplicationAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating COM+ application &quot;{0}&quot;....
        /// </summary>
        internal static string COMCreateApplicationCreating {
            get {
                return ResourceManager.GetString("COMCreateApplicationCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting old COM+ application &quot;{0}&quot;....
        /// </summary>
        internal static string COMCreateApplicationDeleting {
            get {
                return ResourceManager.GetString("COMCreateApplicationDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : COM+ component {0} not be found in {1}. Property {2}={3} will not be applied..
        /// </summary>
        internal static string COMCreateApplicationWarningComponentNotFound {
            get {
                return ResourceManager.GetString("COMCreateApplicationWarningComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting COM+ application &quot;{0}&quot;....
        /// </summary>
        internal static string COMDeleteApplicationDeleting {
            get {
                return ResourceManager.GetString("COMDeleteApplicationDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM+ application &quot;{0}&quot; not found..
        /// </summary>
        internal static string COMDeleteApplicationNotFound {
            get {
                return ResourceManager.GetString("COMDeleteApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering &quot;{0}&quot;....
        /// </summary>
        internal static string ComRegister {
            get {
                return ResourceManager.GetString("ComRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM+ application &quot;{0}&quot; not found..
        /// </summary>
        internal static string COMStartApplicationNotFound {
            get {
                return ResourceManager.GetString("COMStartApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting COM+ application {0}....
        /// </summary>
        internal static string COMStartApplicationStarting {
            get {
                return ResourceManager.GetString("COMStartApplicationStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM+ application &quot;{0}&quot; not found..
        /// </summary>
        internal static string COMStopApplicationNotFound {
            get {
                return ResourceManager.GetString("COMStopApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping COM+ application {0}....
        /// </summary>
        internal static string COMStopApplicationStopping {
            get {
                return ResourceManager.GetString("COMStopApplicationStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering &quot;{0}&quot;....
        /// </summary>
        internal static string ComUnregister {
            get {
                return ResourceManager.GetString("ComUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Environment directory....
        /// </summary>
        internal static string CreatePackageCopyEnvDirectory {
            get {
                return ResourceManager.GetString("CreatePackageCopyEnvDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing {0} folder..
        /// </summary>
        internal static string EnvIncludeMissingEnvDir {
            get {
                return ResourceManager.GetString("EnvIncludeMissingEnvDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files where included..
        /// </summary>
        internal static string EnvIncludeNoInclude {
            get {
                return ResourceManager.GetString("EnvIncludeNoInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing assembly {0} into the GAC....
        /// </summary>
        internal static string GacInstallInstalling {
            get {
                return ResourceManager.GetString("GacInstallInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing assembly {0} from the GAC....
        /// </summary>
        internal static string GacUninstallRemove {
            get {
                return ResourceManager.GetString("GacUninstallRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing sn.exe.
        /// </summary>
        internal static string GenerateInteropErrorExecutingSn {
            get {
                return ResourceManager.GetString("GenerateInteropErrorExecutingSn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing TlbImp.exe.
        /// </summary>
        internal static string GenerateInteropErrorExecutingTlbimp {
            get {
                return ResourceManager.GetString("GenerateInteropErrorExecutingTlbimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} seems up to date with {1} - doing nothing..
        /// </summary>
        internal static string GenerateInteropUpToDate {
            get {
                return ResourceManager.GetString("GenerateInteropUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPool &quot;{0}&quot; already exists..
        /// </summary>
        internal static string IISAppPoolAlreadyExists {
            get {
                return ResourceManager.GetString("IISAppPoolAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating VDir {0}/{1}....
        /// </summary>
        internal static string IISCreateVDirCreate {
            get {
                return ResourceManager.GetString("IISCreateVDirCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Website {0} with ID {1}....
        /// </summary>
        internal static string IISCreateWebSiteCreate {
            get {
                return ResourceManager.GetString("IISCreateWebSiteCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating AppPool {0}....
        /// </summary>
        internal static string IISCreateWebSiteCreateAppPool {
            get {
                return ResourceManager.GetString("IISCreateWebSiteCreateAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating VDir {0}....
        /// </summary>
        internal static string IISCreateWebSiteCreateVDir {
            get {
                return ResourceManager.GetString("IISCreateWebSiteCreateVDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating web file {0}....
        /// </summary>
        internal static string IISCreateWebSiteCreateWebFile {
            get {
                return ResourceManager.GetString("IISCreateWebSiteCreateWebFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting VDir {0}/{1}....
        /// </summary>
        internal static string IISDeleteVDirDelete {
            get {
                return ResourceManager.GetString("IISDeleteVDirDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting website {0}....
        /// </summary>
        internal static string IISDeleteWebSiteDeleting {
            get {
                return ResourceManager.GetString("IISDeleteWebSiteDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting apppool {0}....
        /// </summary>
        internal static string IISDeleteWebSiteDeletingAppPool {
            get {
                return ResourceManager.GetString("IISDeleteWebSiteDeletingAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website {0} not found..
        /// </summary>
        internal static string IISWebSiteNotFound {
            get {
                return ResourceManager.GetString("IISWebSiteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website ROOT {0} not found..
        /// </summary>
        internal static string IISWebSiteRootNotFound {
            get {
                return ResourceManager.GetString("IISWebSiteRootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to kill process {0} : {1}..
        /// </summary>
        internal static string KillProcessError {
            get {
                return ResourceManager.GetString("KillProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found process {0} blocking dll {1} - killing....
        /// </summary>
        internal static string KillProcessFoundProcess {
            get {
                return ResourceManager.GetString("KillProcessFoundProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing process {0}....
        /// </summary>
        internal static string KillProcessKill {
            get {
                return ResourceManager.GetString("KillProcessKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for processes blocking {0}....
        /// </summary>
        internal static string KillProcessSearching {
            get {
                return ResourceManager.GetString("KillProcessSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List {0} not found..
        /// </summary>
        internal static string ListLoopListNotFound {
            get {
                return ResourceManager.GetString("ListLoopListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} doesn&apos;t exists..
        /// </summary>
        internal static string MissingDirectory {
            get {
                return ResourceManager.GetString("MissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} doesn&apos;t exists..
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing action {0} on msi {1}....
        /// </summary>
        internal static string MsiExecAction {
            get {
                return ResourceManager.GetString("MsiExecAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access rule found matching {0} on {1}..
        /// </summary>
        internal static string RemoveAccessRuleEmpty {
            get {
                return ResourceManager.GetString("RemoveAccessRuleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing access rule for {0} on {1}....
        /// </summary>
        internal static string RemoveAccessRuleRemoving {
            get {
                return ResourceManager.GetString("RemoveAccessRuleRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : source dll {0} not found..
        /// </summary>
        internal static string ReplaceComDllSourceError {
            get {
                return ResourceManager.GetString("ReplaceComDllSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding unversioned sources file from {0} to SVN..
        /// </summary>
        internal static string SVNAdding {
            get {
                return ResourceManager.GetString("SVNAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} checked out at {1}..
        /// </summary>
        internal static string SVNCheckedOut {
            get {
                return ResourceManager.GetString("SVNCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out {0} to {1}....
        /// </summary>
        internal static string SVNCheckingOut {
            get {
                return ResourceManager.GetString("SVNCheckingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; is not empty..
        /// </summary>
        internal static string SVNCheckoutEmptyDirectory {
            get {
                return ResourceManager.GetString("SVNCheckoutEmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing {0} for &quot;{1}&quot;....
        /// </summary>
        internal static string SVNCommitCommitting {
            get {
                return ResourceManager.GetString("SVNCommitCommitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} committed at revision {1} by {2}..
        /// </summary>
        internal static string SVNCommitResult {
            get {
                return ResourceManager.GetString("SVNCommitResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are conflicts in the directory {0}..
        /// </summary>
        internal static string SVNConflict {
            get {
                return ResourceManager.GetString("SVNConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} to {1}....
        /// </summary>
        internal static string SVNCopyCopying {
            get {
                return ResourceManager.GetString("SVNCopyCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copied to {1} at revision {2} by {3}..
        /// </summary>
        internal static string SVNCopyResult {
            get {
                return ResourceManager.GetString("SVNCopyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}.
        /// </summary>
        internal static string SVNDelete {
            get {
                return ResourceManager.GetString("SVNDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to evaluate tags uri for uri {0}..
        /// </summary>
        internal static string SVNFunctionsBadBaseUriForTags {
            get {
                return ResourceManager.GetString("SVNFunctionsBadBaseUriForTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources folder ({0}) not found. Ignore adding unversioned sources file to SVN..
        /// </summary>
        internal static string SVNSourcesFolderNotFound {
            get {
                return ResourceManager.GetString("SVNSourcesFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated at revision {1}..
        /// </summary>
        internal static string SVNUpdateResult {
            get {
                return ResourceManager.GetString("SVNUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}....
        /// </summary>
        internal static string SVNUpdateUpdating {
            get {
                return ResourceManager.GetString("SVNUpdateUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing version information. You must either define a property named {0}, used the &lt;version /&gt; task or set the version property..
        /// </summary>
        internal static string VB6UpdateVersionMissingVersion {
            get {
                return ResourceManager.GetString("VB6UpdateVersionMissingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating project &quot;{0}&quot; to version {1}....
        /// </summary>
        internal static string VB6UpdateVersionUpdating {
            get {
                return ResourceManager.GetString("VB6UpdateVersionUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} = {1}.
        /// </summary>
        internal static string VersionSet {
            get {
                return ResourceManager.GetString("VersionSet", resourceCulture);
            }
        }
    }
}
